var data = [
    "富强民主文明和谐, 自由平等公正法治, 爱国敬业诚信友善",
    "绿水青山就是金山银山",
    "为中华之崛起而读书!",
    "减轻义务教育阶段学生作业负担、减轻校外培训负担",
    "实践是检验真理的唯一标准",

    "<a id=quote href=https://www.bilibili.com/video/BV1vW411g7tN>谁甘人生黯淡无光 谁愿做叶不争艳芳</a>",
    "Fly high my friend, until we meet again",
    "HsCnPtPSrYZn",
    "李无用地瓜碱水, 硒钫铕𬭶鿔合金",
    "我这人有几个缺点: 第一, 不会数数; 第二, 记性不好; 第四, 不会数数",
    "圈纸带回家研磨了",
    "我们从这里启航♫",
    "Reduce the frequency of your Github CI crontab to protect the environment.",

    "May the --force be with you",
    "<a id=quote href=https://suckless.org>Software that sucks less</a>",
    "Can’t keep up! Is the server overloaded?\nRunning 5000ms or 100 ticks behind",
    "大炮做好了不放珍珠是什么意思?",
    "write terrible nonsensical code to\nensure the Copilot doesn't take over as captain",
    "<a id=quote href=https://www.curseforge.com/minecraft/mc-mods/carpet>NOT VANILLA!</a>",
    "<a id=quote href=404.html>Big Brother is Watching You</a>",
    "衬衫的价格是9磅15便士",
    "李彦宏: 我想中国人可以更加开放，对隐私问题没有那么敏感。\n如果他们愿意用隐私交换便捷性，很多情况下他们是愿意的。",
    "<a id=quote href=https://wiki.evageeks.org/A.T._Field>AT&T field</a>",
    "I □ Unicode",
    "<a id=quote href=damn_tencent_meeting>有什么业务是腾讯不做的吗?!</a>",
    "Your text editor runs in a web browser,\nMy web browser runs inside a text editor,\nWe are not the same",
    "免费服务的代价就是你自己",
    "<a id=quote href=https://www.openbsd.org/lyrics.html#62>The only change that was required was a three-line diff</a>",
    "<a id=quote href=https://www.gnu.org/music/free-software-song.en.html>GNU SLASH MUZIC</a>",
    "<a id=quote href=https://book.bsdcn.org/di-19-zhang-wen-xue-gu-shi/di-19.3-jie-linux-yu-ku-nan-zhe-xue.html>FreeBSD 拼写有四样写法，你知道么？”，“不能写罢？……我教给你，记着！\n‘FreeBSD’、‘freeBSD’、‘Freebsd’、‘freebsd’这些字应该记着。\n以后做 FreeBSD 管理员的时候，写文档要用。</a>",
    "不要说我们一无所有, 我们要把世界格式化",
    "<a id=quote href=https://www.bilibili.com/video/BV1Ho4y1b7E8>不是你把你那破代码发到 GitHub, 你就是开源软件开发者, 你那个最多叫<b>网络垃圾制造者</b></a>",
    "I'm using Linux. A library that emacs uses to communicate with Intel hardware.",
    "TERRAIN, TERRAIN, PULL UP... dongdigua experienced kinetic energy",
    "Minecraft 1.1⑨.84 The Chat Report Update",
    "<a id=quote href=https://www.bilibili.com/video/BV1gp4y197gm>全物品仓库是一个物资集散中心, 同时它也是个万能垃圾桶</a>",
    "书中自有元素周期表",
    "<a id=quote href=https://www.bilibili.com/video/BV1JY411W7pQ>如果你能在浪费时间中获得乐趣, 那么你就不是在浪费时间</a>",
    "Nice terrain, see you soon!",
    "<ruby>静<rp>(</rp><rt>static</rt><rp>)</rp></ruby>",
    "<a id=quote href=https://cascade.moe/posts/arch-with-zfs/>你说的对，但 ZFS 是一款由 Sun Microsystems 自主研发的一款全新卷系统管理器和文件系统。\n文件系统运行在一个被称作「Linux」的幻想世界，在这里，被 root 选中的存储池将被授予「lz4」，导引存储之力。\n你将扮演一位名为「系统管理员」的神秘角色，在自由的 zpool create 中邂逅功能各异、feature 独特的 vdevs 们，\n和他们一起「state: DEGRADED」，找回失散的数据集——同时，逐步发掘 「BtrFS」 的真相……</a>",
    ":: Starting full system upgrade...\n  there is nothing to do"
];

var index = Math.floor((Math.random() * data.length));
window.document.getElementById("quote").innerHTML = "\"" + data[index] + "\"";
