#+TITLE: Arch 滚挂二三事
#+DATE: <2024-03-24 日>
#+OPTIONS: \n:t

今儿早 Arch 滚挂了，遂打算开一个长期更新主题，记录计算机维修艺术。

* 2024-03-24
一周没滚 Arch，早上八点多一滚，挂了！首先是更新时报错：
#+BEGIN_EXAMPLE
[2024-03-24T08:30:37+0800] [ALPM] running 'gdk-pixbuf-query-loaders.hook'...
[2024-03-24T08:30:37+0800] [ALPM-SCRIPTLET] /usr/bin/gdk-pixbuf-query-loaders: /usr/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /usr/lib/libgio-2.0.so.0)
[2024-03-24T08:30:37+0800] [ALPM] running 'gio-querymodules.hook'...
[2024-03-24T08:30:37+0800] [ALPM] running 'glib-compile-schemas.hook'...
[2024-03-24T08:30:37+0800] [ALPM-SCRIPTLET] /usr/bin/glib-compile-schemas: /usr/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /usr/lib/libgio-2.0.so.0)
[2024-03-24T08:30:37+0800] [ALPM] running 'gtk-update-icon-cache.hook'...
[2024-03-24T08:30:37+0800] [ALPM-SCRIPTLET] gtk-update-icon-cache: /usr/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /usr/lib/libgio-2.0.so.0)
#+END_EXAMPLE
然后一堆程序报错：
#+BEGIN_EXAMPLE
/usr/lib/libmount.so.1: version `MOUNT_2_40' not found (required by /usr/lib/libgio-2.0.so.0)
#+END_EXAMPLE
重启直接进不去桌面了，也连不上网了（NetworkManager）。
我手里的 Arch 镜像还因为太老被我从 Ventoy 删掉了（没错，作为 Arch 用户这很尴尬），
我就启动原来的 Fedora 系统下了个最新的 =util-linux-libs= 包替换掉老的 =libmount.so= （这个操作不要学，有危险，可以直接安装本地包），能联网了，再更新一遍。
但 gdm 进去白屏 =:(= 脸，nautilus 也不能启动，log 都指向了 gsettings schema，
所以就重装任意一个 gnome 程序（比如 nautilus），pacman 就会运行相应的 hook。

这次滚挂的原因我猜可能国内源同步的时候 =glib2= 已经更新了，但 =util-linux-libs= 还没，然后恰好被我赶上了……
#+BEGIN_EXAMPLE
util-linux-libs 2.40rc2-1 Last Updated: 	2024-03-23 23:34 UTC
glib2 2.80.0-2            Last Updated: 	2024-03-23 22:55 UTC
#+END_EXAMPLE

* 2024-07-06
这周不知道哪次更新之后开机就没声了，得按两次静音键才有声。
搜了一下 Arch Linux Forum，删一下 =wireplumber= 缓存?
#+BEGIN_SRC shell
rm -r .local/state/wireplumber/
#+END_SRC
不行，下下次还会有问题，#archlinux-cn 也有几个人有此问题
#+BEGIN_EXAMPLE
07/28
nichi_bot  [影翼] > <@matterbridge:nichi.co> [dongdigua] 那天开机没声音的问题我发了个贴
           https://bbs.archlinux.org/viewtopic.php?id=298114
nichi_bot  [影翼] pipewire的bug，等上游修吧
dongdigua  上游 bug 链接？
nichi_bot  [影翼] > <@matterbridge:nichi.co> [dongdigua] 上游 bug 链接？
nichi_bot  [影翼] 往上翻记录
nichi_bot  [影翼] 很多天前提到的
#+END_EXAMPLE
#+BEGIN_EXAMPLE
│07/16       dongdigua  请问 pipewire 开机后没有声音，必须按两下静音键才有声为啥？尝试删 .local/state/wireplumber
│07/25       nichi_bot  [None None] 应该是 pipewire 的问题
│17:52       nichi_bot  [oldherl] > <None None> 应该是 pipewire 的问题
│07/26       nichi_bot  [Aalivexy] 发现好像是因为pipewire的新Bug
│            nichi_bot  [Aalivexy] https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4084
#+END_EXAMPLE
solved

* 2025-06-23
#+BEGIN_EXAMPLE
error: failed to commit transaction (conflicting files)
linux-firmware-nvidia: /usr/lib/firmware/nvidia/ad103 exists in filesystem
#+END_EXAMPLE
今天不知道 pacman 抽什么疯，要安 nvidia 驱动。
哦，没看 RSS：https://archlinux.org/news/linux-firmware-2025061312fe085f-5-upgrade-requires-manual-intervention/

* 2025-09-??
https://bbs.archlinux.org/viewtopic.php?pid=2271663
需要安装 =xdg-desktop-portal-gtk=
依云说是 gtk4 更新了，导致不使用 portal 就用不了
然后配一下 .config/xdg-desktop-portal/portals.conf
#+BEGIN_EXAMPLE
[preferred]
org.freedesktop.impl.portal.Settings=darkman;gtk
#+END_EXAMPLE
总算是赏心悦目了
