#+TITLE: 狗日的腾讯会议
#+DESCRIPTION: 有什么业务是腾讯不做的吗
#+DATE: <2022-12-02 五>

#+BEGIN_SRC text
上网课有感而发
由于本文是全中文, 所以可能会有人转载
故再次声名: 本文以 CC BY-NC-SA 许可发布, 转载请注明原作者: dongdigua
这篇文章欢迎传播, 但是传播必须要符合许可协议
#+END_SRC

腾讯会议真的是越来越糟糕了!
正如我造就预料到的: 变成像屎一样是腾讯家软件发展的必然

它现在如此"成功"的原因和其他腾讯系软件一样, 趁着国内某些方面软件技术的空白, 赶紧抄袭国外的技术!
凭借这大量的码农和"大公司的可信度", 吸引一大批用户并让他们对其产生依赖后, 开始收割!

我自认为我上网课的历程算是见证了腾讯会议的发家史, 也是疫情宅家才让我接触到互联网的大千世界.
自疫情上网课, 我就一直用腾讯会议, 但同时也用瞩目, 那个传奇的 [[https://zoom.us][Zoom]] 的国内版,
这种洋软件被对待的房事也是很普遍--不是被挡在长城外, 就是产生一个[[https://www.kookapp.cn/][奇妙]]的国内版.

当时, 每当瞩目更新一个新功能(实际上是 Zoom), 腾讯会议总能在一个月左右跟进, 你出一个我抄一个.
虽然我才刚入坑互联网, 却也与同学们得出了"腾讯会议抄袭瞩目"这一有趣的结论.
现在看来, 这太正常了, 抄袭就是腾讯家的一贯作风!

又过了很长一段时间, 再上网课时, 发现腾讯会议加了"啸应用",
那时我已经对腾讯的发家史了解很多了, 觉得这简直太正常了, 国内互联网"大厂"最爱干的就是小程序.
所以我觉得还能让人忍受, 不就是继 WeeChatOS 之后又一个 T_{encent}M_{eeting}OS 嘛...

不, 格局小了! 接下来发生的事才叫一个有趣, 才算的上腾讯真正的优良传统.

现在, 视频选项中加了美颜, 加了头饰, 完美契合了中国网民的虚荣心.
不出所料, 头饰收费, 诶, 有那个占了 0.2G 内置 UE4 引擎的焯级QQ秀那味了.
虚拟背景, 自定义背景是"限免", 那就是下一步要收费喽.
那我觉得腾讯下一步可以把 Live2D 从别的软件扒出来加进去, 皮肤再收个费, 完美!
当然, 作为卑微的普通学生用户, 能正常上课就行了, 不管那些时髦东西.

接下来才是我写这篇文章骂腾讯的直接原因: 连正常上课都, 得加钱!
曾经全国线上授课办公, 钉钉还没完全崛起, 腾讯会议绝对是网课主力军.
当时除了人数有免费限制(我记得是100人)外, 也没什么别的要钱的地方.
而现在, 只有部分地区上网课, 结果免费的只能 *三个人* 开摄像头!!!
这缺的不是资源, 是良心!

当然, 学生乐意了, 因为在老师意识到必须交钱之前可以有正当理由不开摄像头...

解决方案? 当然有很多开源免费高质量的会议软件和服务,
但是人们大多不想改变, 甘愿在屋檐下低头.

看着老师桌面上 Office 2006, 满屏悬浮球, 中国特供版 Flash, 至于 360, 见怪不怪了,
还有对面班级电脑上盘踞着的邪恶蓝章鱼(2345)...
他们没有想过也没有能力让自己的电脑为自己所用, 意识不到自己在被垃圾软件控制着.
又如何进行变革呢?

这种关系国民教育的关键领域, 由这种坑钱公司控制着,
但要是让"官方"来呢? 便成[[https://www.pep.com.cn][人教版Pad]]那种[[https://www.bilibili.com/video/BV1cT411V7Vu][熊样]]
(如果有人能在档案馆找到网页存档, 欢迎联系添加)

希望, 在我们这一代网民!
"青年人要立大志, 而不要励志进大厂", 希望同学们将来真正为中国软件技术作出贡献,
而不是去大厂做那些坑人的, 骗钱的, 破坏别人电脑的, 违背良心的, 无意义的工作.

最后, 让我们畅想一个富有中国特色开源软件的生态吧(暂时没找到原作者):
- VSCode 中国版需手机扫码登录
- npm install 默认 50KB 每秒, 想加速请开通 npm 网盘会员
- Github 分 "高速下载, 离线下载, 本地下载" 等 5 个按钮,
  未登录用户每小时仅限 clone 一个仓库, 同时点击下载后随机弹窗广告
- Stack Overflow 支持付费推广回答, 可长期置顶莆田系统培训版招生信息
- TypeScript 泛型仅限微软注册会员使用, 升级黄金 VIP 可解锁类型体操递归上限
- 前端 UI 库内置贪玩蓝月广告, 支持付费关闭
- 免费用户 gcc 编译 -j 并发数限制为 1, 需并行编译者欢迎打赏开通 GNU 大会员
- Android Studio 深度集成反诈骗中心, 将反诈功能编译进每一个 APK
