#+TITLE: 玩转邮件列表
#+DESCRIPTION: 不只是支线任务
#+DATE: <2023-02-09 四>

这些内容最开始是放在 [[./whatif_openbsd.org][OpenBSD 那篇文章]] 里面的,
但是写的越来越多, 而且与系统本身关系不大, 所以就拿出来单独作为一篇文章.

* email
:PROPERTIES:
:CUSTOM_ID: email
:END:

既然在一个传统 UNIX 上, 那就试试终端邮件客户端, 然后试试订阅 OpenBSD 邮件列表.
然后就按照这篇文章里面配置 smtpd 和 mail,
试了好久都不行, 好乱.
那就试试别的? 我切回 Fedora 看了几个 YouTube 视频, 里面都用 ssmtp, 那就试试?
也试了好久, 发现是网易邮箱不支持 starttls! 估计 smtpd 也是这个原因.

然后切回 OpenBSD, 没有 ssmtp? 那试试传说中的 mutt 吧!
文档还是得看 [[https://wiki.archlinux.org/title/Mutt][ArchWiki]]
这有一篇很好的文章: https://coda.world/neomutt

经过上面那两个摧残之后 mutt 配置感觉容易多了(注意启用 sasl), 很容易就发出了第一封邮件, 然后是怎么收邮件.
smtp 收不了邮件, 得用 pop 或 imap.

然后网易的 imap 有这个恶心东西: RFC 2971 的 ID 指令
#+BEGIN_EXAMPLE
SELECT Unsafe Login. Please contact kefu@188.com for help
#+END_EXAMPLE
我用网易只是因为我有这么一个闲邮箱,
网易整个邮箱网站我感觉挺糟糕的, 一堆广告, 各种帮助页面都 404...
而且我 openbsd 的邮件好长时间才送到, 不知道之后会不会丢邮件...
鬼!

那看看有什么比较好的, 上知乎一顿搜, 最后感觉 zoho mail 还可以.
注册了一下, 配置和说明特别明了,
密码也不是难记的 app 密码, 就是邮箱密码, 5 分钟就搞定 smtp+imap!
再简单弄一下 gpg 加密, 能用了!

头一次自己配邮件客户端, 真学到了很多!

然后, 又是收不到邮件? 试了 mail.com, 不给中国注册. 
最后发现, 不在 INBOX, 而在 Notification...

** dmesg
邮件配置好了, 按照 [[https://www.openbsd.org/faq/faq4.html#SendDmesg][FAQ4]], 把 dmesg 发给 mailto:dmesg@openbsd.org , 帮助开发者更好地支持硬件
我的标题是
#+BEGIN_QUOTE
Lenovo V15 G2 laptop, i915 driver cannot TearFree, Intel Wireless-AC 9560 recognized as Intel Wi-Fi 6 AX201
#+END_QUOTE

然后我又发现了[[https://www.mail-archive.com/misc@openbsd.org/msg162300.html][这个讨论]], dmesg@openbsd.org 只是开发者可见, 公开的看 [[https://dmesgd.nycbug.org/index.cgi][NYCBUG]]

** thread
我用 =set sort=thread= 按照帖子排序成树,
但是我发现根帖子只有 Re 的, 是什么 bug 吗?
然后我发现, INBOX 里只有 Re, 被回复的原邮件都在 Notification...
所以我就删除 Notification 文件夹, 好了... 吗?

** delay
:PROPERTIES:
:ID: delay
:END:

删了 Notification 然后就收不到邮件了!
检查这个事的时候发现漏了不少邮件(跟网页对比), 这怎么行!
唉, .cn 中国特供版...
群里有人推荐 mail.ru, 加上我之前看[[https://iceguye.com][冰姐]]也用, 那就试试?
又在 CSDN (第一个跳出来, ublacklist 不好使) 看到一个转载文章 [[https://web.archive.org/web/20220817110804/https://bawodu.com/zoho-mail-ru-yandex/][5款免费国外域名邮箱Mail.ru, Yandex, Zoho, 25Mail.St, Postale]]
(我就觉得不可能是原创, 文章质量怎么能那么高)

emm, 看起来还算靠谱, 只是俄文读不明白.
试了一下, 收发特别快, 不像国内邮件服务商那样磨磨蹭蹭, 就是我这边访问不够快.
或许我要弄个 offlineimap, 暂时懒得弄了.
还有就是切换文件夹不能从 imap 根目录, 得用比如 ==INBOX=

然后我发现 mail.ru 也丢邮件[[#mailru]]

* mailing list
:PROPERTIES:
:CUSTOM_ID: list
:END:

关于是否 CC, 我第一次 CC 了, 根据我看到其他邮件的总结.
CC 的邮件会在 mutt 里面有 =T= 标记, 但是会有两份.
在 [[https://marc.info/?l=openbsd-misc&m=167553523126610&w=2][Re: Live stick / cd from official sources]] 里面他说
#+BEGIN_QUOTE
No need to cc: me. I's subscribed to misc@.
#+END_QUOTE
+所以我要不要 CC? 不幸的是, 我没收到前一封邮件, 而网页版没法看到底怎么 CC 的...+
+但至少我觉得特别须要提醒的要 to 那个人并 CC 邮件列表.+
to 并 cc 是对的, 这样如果这是一个有很多回复的 thread, 不会弄乱回复树

** [[https://marc.info/?t=167575668100001&r=1&w=2][Cannot use Intel Tearfree on Lenovo V15 G2 laptop]]
:PROPERTIES:
:CUSTOM_ID: intel
:END:
头一次在邮件列表发声, 真不错, 十分滴核邪铀碍, 很块得到了解决方案.
** [[https://marc.info/?t=167576751200001&r=1&w=2][keyboad left ALT not working on console - thinkpad t410]]
遇到了相同问题, 并解决了!
这个邮件的回复等半天(真的是半天12h)还没送到[id:delay], 我是手动下载下来然后 =mutt -f marc.mbox= 回复的
** [[https://marc.info/?t=167599483300001&r=1&w=2][Why some mail were lost, is this common?]]
:PROPERTIES:
:CUSTOM_ID: mailru
:END:
换 OpenMbox.net 了, 希望是最后一次换邮件服务商
(2023.5) OpenMbox 不提供 IMAP/SMTP 了
(2024.1) cock.li 开放注册了竟然! 为了能发邮件需要在浏览器完成 PoW 算法, 这招很聪明地避免了滥用.
** [[https://www.mail-archive.com/misc@openbsd.org/msg184084.html][Live stick / cd from official sources]]
:PROPERTIES:
:CUSTOM_ID: livecd
:END:
2023.2 讨论最火的一个帖子了, 提到这个链接不错: https://liveusb-openbsd.sourceforge.io
我用 mail-archive.org 因为能看回复树, 我邮件收不全, 从 marc 下载再手动 =link-threads= 真的太累了..
这个 my25mb, 似乎是个中国人, 真的是大闹邮件列表.
** [[https://marc.info/?l=openbsd-misc&m=167785692131164&w=2][openbsd get really hot/warm]]
又一个别人跟我遇到相同问题然后我顺便解决了我的问题

