#+TITLE: Minecraft 随想录#1 衰落的服务器
#+DATE: <2024-09-15 日>
#+OPTIONS: \n:nil
#+HTML_HEAD_EXTRA: <link rel="shortcut icon" href=/images/observer_front.png>

#+BEGIN_EXAMPLE
我是一个 1.16.5 入坑的不太老的玩家，对那之前的历史不甚了解，并且视角有限，观点可能会很片面。
如有值得讨论的地方，欢迎发邮件。
#+END_EXAMPLE

暑假最后，我又登入了 PPP 服务器，没有人，全物品似乎完工了，但是竟然没开伪和平。
四处飞飞，感觉和两年前的别无二样。成怀旧服了。
(UPDATE: 似乎 PPP 服准备更新 1.21 了，中秋在炸四连女巫空置域)
许多感想顿时涌上心头：MC 现在怎么了？

我曾经加入过的服务器：土豆 1.18 探索服，关了；打火石服，想当年一群人玩永夜 RPG 和特别行动小游戏，现在基本没人；
PPP 三服联合服，似乎凉了；FantasyZone，我曾经参与过技术生存速通，关了；还有，我，作为第一任物理服主，亲手开的 VasTech，一周上线不超过 10 人次。

除了这些，我最开始关注的那一批 TIS，SST，SciCraft 等技术生存玩家，好像很少有再更新 MC 内容了，我多么希望能再看到 一颗萝卜CarrotLee 和 ilmango 更新视频呀！
现在占据着视频推荐的，却是难以形容的“赤石科技”。

为什么会变成这样？

* 缺少大更新
感觉 1.20 和 1.21 的更新特别水，没有什么革命性的改变，却加入了很多收集性的：盔甲纹饰，全狼收集等。
最近又声明说要减慢大更新的频率。感觉 mojang 的灵感在 1.16 用光了，这样的更新只会减少玩家的热情，修复了游戏有人玩的 bug。
再看看 1.14 和 1.16，我认为两个革命性的版本，当时涌现出了大批比较成功的服务器，就是因为有太多新机制可探索了。

* 疫情后生活回归正轨
虽说玩家热情和更新内容有关，但不可排除疫情时人们闲下来才有时间玩得那么出色。
现在生活忙了，玩游戏的时间少了。一个明显的感觉就是直播变少了。

* 缺少建筑会使玩家缺少归属感
在服务器的工业基础完成差不多之后，如果没有建筑跟进，那么玩家的热情就很快会被无聊冲淡。
在生电火起来之后，许多新兴服务器都不很重视建筑，整个服务器就像个大工厂。
一方面由于许多玩家入坑上来就学生电，而没有老玩家的建筑积淀。
还有就是生电过于成熟使得发展过于急功近利和模式化，前期全服都在发展科技树，没几个人造建筑，后期也不太可能造。
服务器的建筑群才是服务器的特色，在生电如此平民化和公式化的时代，这个服有的机器，别的服也有，单人档也有，那么非要来这个服玩的原因就是建筑。
一个服独特的建筑群会给人家的感觉，也就是上面提到的归属感。

* 人们的生活轨迹会改变，关服是宿命
生电服和小游戏服不一样，人员不会有频繁的更新。
在开荒期加入的人会对服里的各种设施有一个全面的了解，并且有一种归属感。
中后期之后再加入的新人没有之前的经历，很难有这些感觉，他们可能只会溜达几圈，可能会参与一些工程，但更可能的是加入新开荒的服务器重复这一循环。
但几年之后，老玩家们的生活会发生变化，升学，毕业，工作，家庭。他们会慢慢淡出，而新人却越来越难以融入。
根据我几年的观察，一个服务器的声明周期差不多也就两年，很少有服务器发布二周年视频后还活跃着的。
因此脏小豆做了个很明智的选择，没有继续做开放日等给骗赞服拉人，而是开了个未成年骗币服，让热度不衰减。
上面那三点，缺少更新可以旧版本特性再发现，游玩时间短可以招大学生，缺建筑可以建，但这一点是破不了的局。

#+BEGIN_QUOTE
很遗憾，没有什么能成为永恒。在服务器的生命周期里，我们聚是一团火，共同创造世界；散是满天星，继续各自的生活。
多年以后，再打开曾经的存档，或许还会记得和朋友们一起度过的时光，但再也回不来了。
#+END_QUOTE

(本文同时发表于B站专栏 https://www.bilibili.com/read/cv38776164)
