#+TITLE: 记一次帮老师修U盘
#+DESCRIPTION: 驱动器 F 中的磁盘未格式化, 想现在格式化吗?
#+DATE: <2022-11-13 日>
#+OPTIONS: toc:nil num:nil

* 发生甚么事了
老师上课放(U盘里)视频的时候 "啪" 把U盘拔了!
下一次插上就提示 "是否格式化" :)
反正闲时间太多, 我就准备试试给修复一下, 使用我在我文具盒里待了两年的工具箱: [[https://www.ventoy.net][Ventoy]] 启动盘

* 咋整
我首先是对 Linux 文件系统有一定基础, 也进行过不少操作(如多次安装gentoo和arch)
也搞过一些文件系统损坏的事(比如调分区坏过C盘), 还算有经验

于是我上老师电脑启动了两年前放在工具箱盘里的 Fedora Workstation 34

** 第一次尝试
把老师的U盘插上, "嘎嗒"一声熟悉的 gnome 提示音, U盘没显示
有 =/dev/sdc=
=mount -t= 试试? 是不是没文件系统坏了没识别? 不是
=fsck= 试试? 不行
嗯??? 似乎有点超出我的知识储备和经验了
** 第二次尝试
只有一个整盘, 没有分区号? 凭直觉, 我觉得那就是分区表坏了
然后查了一下(当然用英文查), 有没有能修复分区表的? [[https://www.cgsecurity.org][testdisk]]
然后先用 =dd= 整盘备份一下, 跑 testdisk
很简单就把分区表恢复出来了!

那就开始拷文件吧..."文件不完整"
** 第三次尝试
和 testdisk 一家的软件还有 =photorec=, 我似乎在 [[https://linux.cn][linuxcn]] 见过(懒得去找链接了)
这东西一看就知道是通过文件头来识别并恢复文件的
那就跑呗
一节课之后, 文件(和曾经被删除的)都回来了
开心!

* 接活?
:PROPERTIES:
:CUSTOM_ID: ad
:END:
我可以比较廉价的进行数据恢复
联系我后将磁盘镜像传到 FTP 服务器, *不接百度网盘*
暂定价如下:
** 16GiB 以下 0.3 XMR
** 16~64GiB 0.5 XMR

* 后续
恢复完之后我想瞅瞅那些教学视频, 正常来讲 f34 应该有解码器的, 但是没有
是不是我连着网给我删了?
#+BEGIN_COMMENT
一同学有坏的 32G盘(很早之前坏的), 给我恢复

看到是 =/dev/sda1= 知道分区表没坏
不稳定, 总是掉盘(原因可能是过热), 这估计也是坏的原因了, 所以我就 =watch -n 20 ls /dev/sd*= 检查着
先用 dd 备份一份...结果他给我的备份盘是 FAT32, 镜像太大了, 所以就暂时再用 gparted 分一个 NTFS 的分区
...但是总是到 12G 的时候掉盘
那就直接 =fsck.fat -a=? 还是掉盘
我尝试把其中的一个大文件先移动走再 fsck, 但是 "Read-only file system"

emm...硬件问题还是没办法
#+END_COMMENT

